### ISSUE TITLE
Core dump when run without a suitable environment

### ISSUE THREAD

**Issue by pcn** [droundy/fac#6]
I was running with `env -` to see if I could confirm that one of my build scripts would cause an error, and got a core dump:

```
$ ulimit -c 100000000000
(test-fac) $ env - ~/bin/fac -j 1 
1/1 [0.01s]: bash install-into-venv.sh > install.fac
build failed: install.fac                          
Segmentation fault (core dumped)
(test-fac) $ gdb ~/bin/fac
GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/spacey/bin/fac...done.
(gdb) core-file core
[New LWP 2934]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/spacey/bin/fac -j 1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x000055a948f51d4a in read_fac_file (all=all@entry=0x7ffd817930e0, 
    path=path@entry=0x55a94a70a960 "/home/spacey/dvcs/test-fac/packages.fac") at files.c:175
#2  0x000055a948f56f36 in do_actual_build (args=0x7ffd81793220) at build.c:1005
#3  0x000055a948f4fc49 in main (argc=<optimized out>, argv=<optimized out>) at fac.c:121
(gdb) 
```

The path names are changed, but from a quick look at file.c, it looks like at https://github.com/droundy/fac/blob/eebf33606c395b76c1c3d319cd28978eb091ba7a/files.c#L174 `*home` will get  set to a null pointer.  The man page seems to say that in this case `realpath()` should return a null and set errno.

**Comment by droundy** [comment]
Thanks for the bug report, I agree that this is a real bug.  Would you mind, by any chance, writing a test script to demonstrate this?

**Comment by pcn** [comment]
OK, in the PR above.

**Comment by droundy** [comment]
I'm issuing a warning for this case, since we are forced to ignore the C ~/... directive.  I'm not sure this is the right thing to do, but ignoring it doesn't seem like a great option.  Another option would be to exit with an error, but that might not satisfy your use case.
